# Generated by Django 2.2.10 on 2021-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usecasename', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('precondition', models.CharField(max_length=100)),
                ('postcondition', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projectlist',
            },
        ),
    ]
