# Generated by Django 3.2.3 on 2021-05-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_project_projectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='scenariolist',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('scenarioid', models.IntegerField(max_length=100)),
                ('scenariotype', models.CharField(max_length=100)),
                ('postscenarioidyes', models.IntegerField(max_length=100, null=True, blank=True)),
                ('postscenarioidno', models.IntegerField(max_length=100, null=True, blank=True)),
                ('scenario', models.CharField(max_length=100)),
                ('projectno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectlist')),
            ],
            options={
                'db_table': 'scenariolist',
            },
        ),
    ]
