# Generated by Django 2.2.10 on 2021-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scenariolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariolist',
            name='postscenarioidno',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scenariolist',
            name='postscenarioidyes',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scenariolist',
            name='scenariotype',
            field=models.CharField(choices=[('task', 'TASK'), ('conditional', 'Conditional')], default='task', max_length=100),
        ),
    ]
